<a href="https://colab.research.google.com/github/DassV24/neural-network-challenge-2/blob/main/attrition.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Part 1: Preprocessing

In [1]:
!pip install --upgrade tensorflow
!pip install --upgrade keras

In [2]:
                                                                # Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np
from tensorflow.keras.models import Model
from tensorflow.keras import layers
from sklearn.preprocessing import OneHotEncoder

#  Import and read the attrition data
attrition_df = pd.read_csv('https://static.bc-edx.com/ai/ail-v-1-0/m19/lms/datasets/attrition.csv')
attrition_df.head()

Age Attrition     BusinessTravel              Department  DistanceFromHome  \
0   41       Yes      Travel_Rarely                   Sales                 1   
1   49        No  Travel_Frequently  Research & Development                 8   
2   37       Yes      Travel_Rarely  Research & Development                 2   
3   33        No  Travel_Frequently  Research & Development                 3   
4   27        No      Travel_Rarely  Research & Development                 2   

   Education EducationField  EnvironmentSatisfaction  HourlyRate  \
0          2  Life Sciences                        2          94   
1          1  Life Sciences                        3          61   
2          2          Other                        4          92   
3          4  Life Sciences                        4          56   
4          1        Medical                        1          40   

   JobInvolvement  ...  PerformanceRating RelationshipSatisfaction  \
0               3  ...                  3                        1   
1               2  ...                  4                        4   
2               2  ...                  3                        2   
3               3  ...                  3                        3   
4               3  ...                  3                        4   

   StockOptionLevel TotalWorkingYears  TrainingTimesLastYear WorkLifeBalance  \
0                 0                 8                      0               1   
1                 1                10                      3               3   
2                 0                 7                      3               3   
3                 0                 8                      3               3   
4                 1                 6                      3               3   

   YearsAtCompany  YearsInCurrentRole  YearsSinceLastPromotion  \
0               6                   4                        0   
1              10                   7                        1   
2               0                   0                        0   
3               8                   7                        3   
4               2                   2                        2   

   YearsWithCurrManager  
0                     5  
1                     7  
2                     0  
3                     0  
4                     2  

[5 rows x 27 columns]

In [3]:
# Determine the number of unique values in each column.
attrition_df.nunique()

Age                         43
Attrition                    2
BusinessTravel               3
Department                   3
DistanceFromHome            29
Education                    5
EducationField               6
EnvironmentSatisfaction      4
HourlyRate                  71
JobInvolvement               4
JobLevel                     5
JobRole                      9
JobSatisfaction              4
MaritalStatus                3
NumCompaniesWorked          10
OverTime                     2
PercentSalaryHike           15
PerformanceRating            2
RelationshipSatisfaction     4
StockOptionLevel             4
TotalWorkingYears           40
TrainingTimesLastYear        7
WorkLifeBalance              4
YearsAtCompany              37
YearsInCurrentRole          19
YearsSinceLastPromotion     16
YearsWithCurrManager        18
dtype: int64

In [4]:
# Create y_df with the Attrition and Department columns
y_df = attrition_df[['Attrition', 'Department']]
y_df.head()


Attrition              Department
0       Yes                   Sales
1        No  Research & Development
2       Yes  Research & Development
3        No  Research & Development
4        No  Research & Development

In [5]:
# View the types of data
attrition_df.dtypes

Age                          int64
Attrition                   object
BusinessTravel              object
Department                  object
DistanceFromHome             int64
Education                    int64
EducationField              object
EnvironmentSatisfaction      int64
HourlyRate                   int64
JobInvolvement               int64
JobLevel                     int64
JobRole                     object
JobSatisfaction              int64
MaritalStatus               object
NumCompaniesWorked           int64
OverTime                    object
PercentSalaryHike            int64
PerformanceRating            int64
RelationshipSatisfaction     int64
StockOptionLevel             int64
TotalWorkingYears            int64
TrainingTimesLastYear        int64
WorkLifeBalance              int64
YearsAtCompany               int64
YearsInCurrentRole           int64
YearsSinceLastPromotion      int64
YearsWithCurrManager         int64
dtype: object

In [6]:
# Create a list of at least 10 column names to use as X data
X_columns = ['Age', 'HourlyRate', 'DistanceFromHome', 'Education', 'WorkLifeBalance', 'EnvironmentSatisfaction', 'HourlyRate', 'JobInvolvement', 'JobLevel', 'JobSatisfaction']


# Create X_df using your selected columns
X_df = attrition_df[X_columns]

# Show the data types for X_df
X_df.head()


Age  HourlyRate  DistanceFromHome  Education  WorkLifeBalance  \
0   41          94                 1          2                1   
1   49          61                 8          1                3   
2   37          92                 2          2                3   
3   33          56                 3          4                3   
4   27          40                 2          1                3   

   EnvironmentSatisfaction  HourlyRate  JobInvolvement  JobLevel  \
0                        2          94               3         2   
1                        3          61               2         2   
2                        4          92               2         1   
3                        4          56               3         1   
4                        1          40               3         1   

   JobSatisfaction  
0                4  
1                2  
2                3  
3                3  
4                2

In [7]:
# Split the data into training and testing sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_df, y_df, test_size=0.2, random_state=1)


In [8]:
# Convert your X data to numeric data types however you see fit
# X_train = X_train.apply(pd.to_numeric, errors='coerce')
# X_test = X_test.apply(pd.to_numeric, errors='coerce')
# Add new code cells as necessary

In [9]:
# Create a StandardScaler
scaler = StandardScaler().fit(X_train)

# Fit the StandardScaler to the training data
X_train_scaled = scaler.transform(X_train)

# Scale the training and testing data
X_test_scaled = scaler.transform(X_test)


In [10]:
# Create a OneHotEncoder for the Department column
department_onehot = OneHotEncoder(drop=None, handle_unknown='ignore', sparse_output=False)

# Fit the encoder to the training data
department_onehot.fit(y_train['Department'].values.reshape(-1, 1))

# Create two new variables by applying the encoder
# to the training and testing data
y_train_dpt_encoded = department_onehot.transform(np.array(y_train['Department']).reshape(-1, 1))
y_test_dpt_encoded = department_onehot.transform(np.array(y_test['Department']).reshape(-1, 1))

print(f"y_train_dpt_encoded: \n {y_train_dpt_encoded[:5]} \ny_test_dpt_encoded: \n {y_test_dpt_encoded[:5]}")


y_train_dpt_encoded: 
 [[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]] 
y_test_dpt_encoded: 
 [[0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]


In [11]:
# Create a OneHotEncoder for the Attrition column
attrition_onehot = OneHotEncoder(drop=None, handle_unknown='ignore', sparse_output=False)

# Fit the encoder to the training data
attrition_onehot.fit(y_train['Attrition'].values.reshape(-1, 1))

# Create two new variables by applying the encoder
# to the training and testing data
y_train_att_encoded = attrition_onehot.transform(np.array(y_train['Attrition']).reshape(-1, 1))
y_test_att_encoded = attrition_onehot.transform(np.array(y_test['Attrition']).reshape(-1, 1))

# Print shape of encoded results
print(f"y_train_att_encoded: \n {y_train_att_encoded[:5]} \ny_test_att_encoded: \n {y_test_att_encoded[:5]}")


y_train_att_encoded: 
 [[1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]] 
y_test_att_encoded: 
 [[0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]]


## Create, Compile, and Train the Model

In [12]:
# Find the number of columns in the X training data
input_features = X_train_scaled.shape[1]
print(input_features)

# Create the input layer
input_layer = layers.Input(shape=(input_features,))

# Create at least two shared layers
shared_layer_1 = layers.Dense(units=64, activation='relu')(input_layer)
print(shared_layer_1.shape)
shared_layer_2 = layers.Dense(units=32, activation='relu')(shared_layer_1)
print(shared_layer_2.shape)

10
(None, 64)
(None, 32)


In [16]:
# Create a branch for Department
# with a hidden layer and an output layer

# Create the hidden layer
dpt_hidden_layer = layers.Dense(units=16, activation='relu')(shared_layer_2)
print(dpt_hidden_layer)
# Create the output layer
dpt_output_layer = layers.Dense(units=y_train_dpt_encoded.shape[1], activation='softmax', name='Department_Output')(dpt_hidden_layer)
print(dpt_output_layer)

<KerasTensor shape=(None, 16), dtype=float32, sparse=False, name=keras_tensor_6>
<KerasTensor shape=(None, 3), dtype=float32, sparse=False, name=keras_tensor_7>


In [20]:
# Create a branch for Attrition
# with a hidden layer and an output layer

# Create the hidden layer
att_hidden_layer = layers.Dense(units=16, activation='relu')(shared_layer_2)
print(att_hidden_layer)
# Create the output layer
att_output_layer = layers.Dense(units=y_train_att_encoded.shape[1], activation='softmax', name='Attrition_Output')(att_hidden_layer)
print(att_output_layer)

<KerasTensor shape=(None, 16), dtype=float32, sparse=False, name=keras_tensor_12>
<KerasTensor shape=(None, 2), dtype=float32, sparse=False, name=keras_tensor_13>


In [22]:
# Create the model
model = Model(inputs=input_layer, outputs=[dpt_output_layer, att_output_layer])

# Compile the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics={'Department_Output':'accuracy','Attrition_Output':'accuracy'})

# Summarize the model
model.summary()

Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)              ┃ Output Shape           ┃        Param # ┃ Connected to           ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)  │ (None, 10)             │              0 │ -                      │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense (Dense)             │ (None, 64)             │            704 │ input_layer[0][0]      │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense_1 (Dense)           │ (None, 32)             │          2,080 │ dense[0][0]            │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense_5 (Dense)           │ (None, 16)             │            528 │ dense_1[0][0]          │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense_9 (Dense)           │ (None, 16)             │            528 │ dense_1[0][0]          │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ Department_Output (Dense) │ (None, 3)              │             51 │ dense_5[0][0]          │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ Attrition_Output (Dense)  │ (None, 2)              │             34 │ dense_9[0][0]          │
└───────────────────────────┴────────────────────────┴────────────────┴────────────────────────┘

 Total params: 3,925 (15.33 KB)

 Trainable params: 3,925 (15.33 KB)

 Non-trainable params: 0 (0.00 B)

In [31]:
# Train the model
train_model = model.fit(
    X_train_scaled,
    [y_train_dpt_encoded, y_train_att_encoded],
    epochs=100,
    batch_size=32,
    validation_data=(X_test_scaled, [y_test_dpt_encoded, y_test_att_encoded])
    )


Epoch 1/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - Attrition_Output_accuracy: 0.8446 - Attrition_Output_loss: 0.5423 - Department_Output_accuracy: 0.4667 - Department_Output_loss: 1.0598 - loss: 1.6022 - val_Attrition_Output_accuracy: 0.8027 - val_Attrition_Output_loss: 0.4916 - val_Department_Output_accuracy: 0.6327 - val_Department_Output_loss: 0.8799 - val_loss: 1.3904
Epoch 2/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - Attrition_Output_accuracy: 0.8435 - Attrition_Output_loss: 0.4435 - Department_Output_accuracy: 0.6543 - Department_Output_loss: 0.8544 - loss: 1.2979 - val_Attrition_Output_accuracy: 0.8027 - val_Attrition_Output_loss: 0.4686 - val_Department_Output_accuracy: 0.6327 - val_Department_Output_loss: 0.7819 - val_loss: 1.2742
Epoch 3/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - Attrition_Output_accuracy: 0.8277 - Attrition_Output_loss: 0.4446 - Department_Output_accuracy: 0.6449 - Department_Output_loss: 0.7890 - loss: 1.2336 - val_Attrition_Output_accuracy: 0.8027 - 

In [32]:
# Accuracy for both Department_Output and Attrition_Output format for readability
# Evaluate the model with the testing data
results = model.evaluate(X_test_scaled, [y_test_dpt_encoded, y_test_att_encoded])


10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - Attrition_Output_accuracy: 0.7403 - Attrition_Output_loss: 1.0817 - Department_Output_accuracy: 0.5528 - Department_Output_loss: 1.4520 - loss: 2.5512 


In [37]:
# Print the accuracy for both department and attrition
print(f"Total Loss: {results[0]:.4f}")
print(f"Department Loss: {results[1]:.4f}\nDepartment Accuracy: {results[3]:.4f}")
print(f"Attrition Loss: {results[2]:.4f}\nAttrition Accuracy: {results[4]:.4f}")

Total Loss: 2.3168
Department Loss: 1.2687
Department Accuracy: 0.7449
Attrition Loss: 0.9517
Attrition Accuracy: 0.5680


# Summary

In the provided space below, briefly answer the following questions.

1. Is accuracy the best metric to use on this data? Why or why not?

2. What activation functions did you choose for your output layers, and why?

3. Can you name a few ways that this model might be improved?

YOUR ANSWERS HERE

1. No. the results from the modle evaluation indicate a possible imballance classes in the target variables. With high loss it's hard to trust high accuracy, eg. Department Accuracy.
2. I used softmax for the department data because it best suited for multi-class task, and the department has 3 class. I used sigmoid on the attrition data becasue it has two possible outcomes 0 or 1.
3. Balancing the attrition dataset and experimenting with more layers or different sizes. You could also change the dimensions.

In [38]:
# Print the Attrition value count to identify imballance.
y_train['Attrition'].value_counts()

Attrition
No     997
Yes    179
Name: count, dtype: int64